### ISSUE TITLE
GPU mining not working

### ISSUE THREAD

**Issue by XrayHunter** [classzz/classzz#3]
Im getting certificate related errors.
-GetWork errPost x509: certificate signed by unknown authority
-GetWork errPost http: server gave HTTP response to HTTPS client
-http: TLS handshake error from xxxxxxxx:49456: remote error: tls: bad certificate
[https://i.imgur.com/8C0Hjcp.png](url)

**Comment by matthew-pro** [comment]
I can't see the picture you sent, could you please send it again
