### ISSUE TITLE
Nonce error, no consensus

### ISSUE THREAD

**Issue by n4kashu** [classzz/classzz#4]
Hi,

I have been trying to start the miner.

I have synced and configured DOGE and LTC nodes.Allowed RPC, all settings standard as I mine towards fullnode RPC. (tls disabled, mining from local GPU, ubuntu 18.04 minimal)

In debug log I see numerous refused connections and miners always gets only:
 
2020/02/21 23:48:28 SubmitWorkerr-25: Nonce error, no consensus

I have tried all possible scenarions, set up onion/tor.. 

any advice would be much appreciated..

Thank you!

**Comment by matthew-pro** [comment]
Is your GPU code compatible with the main network algorithm? So far, the algorithm is not compatible
