### ISSUE TITLE
Why Init Table fail?

### ISSUE THREAD

**Issue by pursonchen** [classzz/classzz#5]
When I run 
```shell
./czzd --configfile="classzz.conf"
```
![Error](https://user-images.githubusercontent.com/17820243/76318278-6e5a5480-6318-11ea-895c-6751a0be500b.png)

#### My config :
```conf
; classzz.conf 
datadir=data 
addpeer=119.3.211.135 
addpeer=119.3.254.147 
rpclisten=0.0.0.0 
whitelist=0.0.0.0 
rpcuser=root 
rpcpass=root
```
```conf
;czzctl.conf
rpcuser=root 
rpcpass=root
```

Can anybody help?

**Comment by matthew-pro** [comment]
The table is 32MB in size, so you can see if the file you downloaded is correct
